import type { BordTheme } from "./types";
export type { BordTheme } from "./types";

export const themes: BordTheme[] = [
  // ── Catppuccin Frappe (default) ──────────────────────────────────────
  {
    id: "catppuccin-frappe",
    name: "Catppuccin Frappe",
    appearance: "dark",
    chrome: {
      bgPrimary: "#232634",
      bgSecondary: "#292c3c",
      bgTertiary: "#414559",
      border: "#51576d",
      textPrimary: "#c6d0f5",
      textSecondary: "#a5adce",
      accent: "#8caaee",
      accentHover: "#babbf1",
      danger: "#e78284",
      success: "#a6d189",
      warning: "#e5c890",
      diffAddBg: "#12261e",
      diffDeleteBg: "#2d1215",
    },
    terminal: {
      background: "#303446",
      foreground: "#c6d0f5",
      cursor: "#f2d5cf",
      cursorAccent: "#303446",
      selectionBackground: "#626880",
      selectionForeground: "#c6d0f5",
      black: "#51576d",
      red: "#e78284",
      green: "#a6d189",
      yellow: "#e5c890",
      blue: "#8caaee",
      magenta: "#f4b8e4",
      cyan: "#81c8be",
      white: "#a5adce",
      brightBlack: "#626880",
      brightRed: "#e67172",
      brightGreen: "#8ec772",
      brightYellow: "#d9ba73",
      brightBlue: "#7b9ef0",
      brightMagenta: "#f2a4db",
      brightCyan: "#5abfb5",
      brightWhite: "#b5bfe2",
    },
  },

  // ── Catppuccin Mocha ─────────────────────────────────────────────────
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    appearance: "dark",
    chrome: {
      bgPrimary: "#11111b",
      bgSecondary: "#181825",
      bgTertiary: "#313244",
      border: "#45475a",
      textPrimary: "#cdd6f4",
      textSecondary: "#a6adc8",
      accent: "#89b4fa",
      accentHover: "#b4befe",
      danger: "#f38ba8",
      success: "#a6e3a1",
      warning: "#f9e2af",
      diffAddBg: "#0f2419",
      diffDeleteBg: "#2b1018",
    },
    terminal: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#585b70",
      selectionForeground: "#cdd6f4",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#a6adc8",
      brightBlack: "#585b70",
      brightRed: "#f37799",
      brightGreen: "#89d88b",
      brightYellow: "#ebd391",
      brightBlue: "#74a8fc",
      brightMagenta: "#f2aede",
      brightCyan: "#6bd7ca",
      brightWhite: "#bac2de",
    },
  },

  // ── Catppuccin Macchiato ─────────────────────────────────────────────
  {
    id: "catppuccin-macchiato",
    name: "Catppuccin Macchiato",
    appearance: "dark",
    chrome: {
      bgPrimary: "#181926",
      bgSecondary: "#1e2030",
      bgTertiary: "#363a4f",
      border: "#494d64",
      textPrimary: "#cad3f5",
      textSecondary: "#a5adcb",
      accent: "#8aadf4",
      accentHover: "#b7bdf8",
      danger: "#ed8796",
      success: "#a6da95",
      warning: "#eed49f",
      diffAddBg: "#10251c",
      diffDeleteBg: "#2c1116",
    },
    terminal: {
      background: "#24273a",
      foreground: "#cad3f5",
      cursor: "#f4dbd6",
      cursorAccent: "#24273a",
      selectionBackground: "#5b6078",
      selectionForeground: "#cad3f5",
      black: "#494d64",
      red: "#ed8796",
      green: "#a6da95",
      yellow: "#eed49f",
      blue: "#8aadf4",
      magenta: "#f5bde6",
      cyan: "#8bd5ca",
      white: "#a5adcb",
      brightBlack: "#5b6078",
      brightRed: "#ec7486",
      brightGreen: "#8ccf7f",
      brightYellow: "#e1c682",
      brightBlue: "#78a1f6",
      brightMagenta: "#f2a9dd",
      brightCyan: "#63cbc0",
      brightWhite: "#b8c0e0",
    },
  },

  // ── Catppuccin Latte (light) ─────────────────────────────────────────
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    appearance: "light",
    chrome: {
      bgPrimary: "#dce0e8",
      bgSecondary: "#e6e9ef",
      bgTertiary: "#ccd0da",
      border: "#bcc0cc",
      textPrimary: "#4c4f69",
      textSecondary: "#6c6f85",
      accent: "#1e66f5",
      accentHover: "#7287fd",
      danger: "#d20f39",
      success: "#40a02b",
      warning: "#df8e1d",
      diffAddBg: "#d4edcf",
      diffDeleteBg: "#f5d0d6",
    },
    terminal: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      cursorAccent: "#eff1f5",
      selectionBackground: "#acb0be",
      selectionForeground: "#4c4f69",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#de293e",
      brightGreen: "#49af3d",
      brightYellow: "#eea02d",
      brightBlue: "#456eff",
      brightMagenta: "#fe85d8",
      brightCyan: "#2d9fa8",
      brightWhite: "#bcc0cc",
    },
  },

  // ── Dracula ──────────────────────────────────────────────────────────
  {
    id: "dracula",
    name: "Dracula",
    appearance: "dark",
    chrome: {
      bgPrimary: "#1e1f29",
      bgSecondary: "#282a36",
      bgTertiary: "#44475a",
      border: "#6272a4",
      textPrimary: "#f8f8f2",
      textSecondary: "#bfbfbf",
      accent: "#bd93f9",
      accentHover: "#d6acff",
      danger: "#ff5555",
      success: "#50fa7b",
      warning: "#f1fa8c",
      diffAddBg: "#132a1c",
      diffDeleteBg: "#2d1219",
    },
    terminal: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      selectionForeground: "#ffffff",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },

  // ── Gruvbox Dark ─────────────────────────────────────────────────────
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    appearance: "dark",
    chrome: {
      bgPrimary: "#1d2021",
      bgSecondary: "#282828",
      bgTertiary: "#3c3836",
      border: "#504945",
      textPrimary: "#ebdbb2",
      textSecondary: "#a89984",
      accent: "#458588",
      accentHover: "#83a598",
      danger: "#cc241d",
      success: "#98971a",
      warning: "#d79921",
      diffAddBg: "#1e2c1a",
      diffDeleteBg: "#2c1a1a",
    },
    terminal: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#665c54",
      selectionForeground: "#ebdbb2",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },

  // ── Nord ─────────────────────────────────────────────────────────────
  {
    id: "nord",
    name: "Nord",
    appearance: "dark",
    chrome: {
      bgPrimary: "#242933",
      bgSecondary: "#2e3440",
      bgTertiary: "#3b4252",
      border: "#4c566a",
      textPrimary: "#d8dee9",
      textSecondary: "#9aa5b9",
      accent: "#81a1c1",
      accentHover: "#88c0d0",
      danger: "#bf616a",
      success: "#a3be8c",
      warning: "#ebcb8b",
      diffAddBg: "#1a2b1e",
      diffDeleteBg: "#2b1a1d",
    },
    terminal: {
      background: "#2e3440",
      foreground: "#d8dee9",
      cursor: "#eceff4",
      cursorAccent: "#282828",
      selectionBackground: "#eceff4",
      selectionForeground: "#4c566a",
      black: "#3b4252",
      red: "#bf616a",
      green: "#a3be8c",
      yellow: "#ebcb8b",
      blue: "#81a1c1",
      magenta: "#b48ead",
      cyan: "#88c0d0",
      white: "#e5e9f0",
      brightBlack: "#596377",
      brightRed: "#bf616a",
      brightGreen: "#a3be8c",
      brightYellow: "#ebcb8b",
      brightBlue: "#81a1c1",
      brightMagenta: "#b48ead",
      brightCyan: "#8fbcbb",
      brightWhite: "#eceff4",
    },
  },

  // ── Tokyo Night ──────────────────────────────────────────────────────
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    appearance: "dark",
    chrome: {
      bgPrimary: "#13141c",
      bgSecondary: "#1a1b26",
      bgTertiary: "#292e42",
      border: "#414868",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      accent: "#7aa2f7",
      accentHover: "#bb9af7",
      danger: "#f7768e",
      success: "#9ece6a",
      warning: "#e0af68",
      diffAddBg: "#12261a",
      diffDeleteBg: "#2d1219",
    },
    terminal: {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#15161e",
      selectionBackground: "#33467c",
      selectionForeground: "#c0caf5",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },

  // ── Tokyo Night Storm ────────────────────────────────────────────────
  {
    id: "tokyo-night-storm",
    name: "Tokyo Night Storm",
    appearance: "dark",
    chrome: {
      bgPrimary: "#1c1e30",
      bgSecondary: "#24283b",
      bgTertiary: "#343a52",
      border: "#4e5575",
      textPrimary: "#c0caf5",
      textSecondary: "#a9b1d6",
      accent: "#7aa2f7",
      accentHover: "#bb9af7",
      danger: "#f7768e",
      success: "#9ece6a",
      warning: "#e0af68",
      diffAddBg: "#14281c",
      diffDeleteBg: "#2e131a",
    },
    terminal: {
      background: "#24283b",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#1d202f",
      selectionBackground: "#364a82",
      selectionForeground: "#c0caf5",
      black: "#1d202f",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#4e5575",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },

  // ── One Dark ─────────────────────────────────────────────────────────
  {
    id: "one-dark",
    name: "One Dark",
    appearance: "dark",
    chrome: {
      bgPrimary: "#1b1d23",
      bgSecondary: "#21252b",
      bgTertiary: "#323844",
      border: "#3e4452",
      textPrimary: "#abb2bf",
      textSecondary: "#7f848e",
      accent: "#61afef",
      accentHover: "#8cc8ff",
      danger: "#e06c75",
      success: "#98c379",
      warning: "#e5c07b",
      diffAddBg: "#16291c",
      diffDeleteBg: "#2a1318",
    },
    terminal: {
      background: "#21252b",
      foreground: "#abb2bf",
      cursor: "#abb2bf",
      cursorAccent: "#21252b",
      selectionBackground: "#323844",
      selectionForeground: "#abb2bf",
      black: "#21252b",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#767676",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#abb2bf",
    },
  },

  // ── Solarized Dark ───────────────────────────────────────────────────
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    appearance: "dark",
    chrome: {
      bgPrimary: "#001219",
      bgSecondary: "#001e27",
      bgTertiary: "#003748",
      border: "#005a6e",
      textPrimary: "#9cc2c3",
      textSecondary: "#7a8f8e",
      accent: "#2176c7",
      accentHover: "#178ec8",
      danger: "#d11c24",
      success: "#6cbe6c",
      warning: "#a57706",
      diffAddBg: "#0a2a1a",
      diffDeleteBg: "#2a0c10",
    },
    terminal: {
      background: "#001e27",
      foreground: "#9cc2c3",
      cursor: "#f34b00",
      cursorAccent: "#002831",
      selectionBackground: "#003748",
      selectionForeground: "#7a8f8e",
      black: "#002831",
      red: "#d11c24",
      green: "#6cbe6c",
      yellow: "#a57706",
      blue: "#2176c7",
      magenta: "#c61c6f",
      cyan: "#259286",
      white: "#eae3cb",
      brightBlack: "#006488",
      brightRed: "#f5163b",
      brightGreen: "#51ef84",
      brightYellow: "#b27e28",
      brightBlue: "#178ec8",
      brightMagenta: "#e24d8e",
      brightCyan: "#00b39e",
      brightWhite: "#fcf4dc",
    },
  },

  // ── Rose Pine ────────────────────────────────────────────────────────
  {
    id: "rose-pine",
    name: "Rosé Pine",
    appearance: "dark",
    chrome: {
      bgPrimary: "#12111e",
      bgSecondary: "#191724",
      bgTertiary: "#26233a",
      border: "#403d52",
      textPrimary: "#e0def4",
      textSecondary: "#908caa",
      accent: "#9ccfd8",
      accentHover: "#c4a7e7",
      danger: "#eb6f92",
      success: "#31748f",
      warning: "#f6c177",
      diffAddBg: "#122226",
      diffDeleteBg: "#2a1420",
    },
    terminal: {
      background: "#191724",
      foreground: "#e0def4",
      cursor: "#e0def4",
      cursorAccent: "#191724",
      selectionBackground: "#403d52",
      selectionForeground: "#e0def4",
      black: "#26233a",
      red: "#eb6f92",
      green: "#31748f",
      yellow: "#f6c177",
      blue: "#9ccfd8",
      magenta: "#c4a7e7",
      cyan: "#ebbcba",
      white: "#e0def4",
      brightBlack: "#6e6a86",
      brightRed: "#eb6f92",
      brightGreen: "#31748f",
      brightYellow: "#f6c177",
      brightBlue: "#9ccfd8",
      brightMagenta: "#c4a7e7",
      brightCyan: "#ebbcba",
      brightWhite: "#e0def4",
    },
  },

  // ── Ayu Mirage ───────────────────────────────────────────────────────
  {
    id: "ayu-mirage",
    name: "Ayu Mirage",
    appearance: "dark",
    chrome: {
      bgPrimary: "#171b24",
      bgSecondary: "#1f2430",
      bgTertiary: "#2b3040",
      border: "#3e4556",
      textPrimary: "#cccac2",
      textSecondary: "#8b8680",
      accent: "#73d0ff",
      accentHover: "#6dcbfa",
      danger: "#f28779",
      success: "#87d96c",
      warning: "#ffd173",
      diffAddBg: "#152518",
      diffDeleteBg: "#2c1514",
    },
    terminal: {
      background: "#1f2430",
      foreground: "#cccac2",
      cursor: "#ffcc66",
      cursorAccent: "#1f2430",
      selectionBackground: "#409fff",
      selectionForeground: "#1f2430",
      black: "#171b24",
      red: "#ed8274",
      green: "#87d96c",
      yellow: "#facc6e",
      blue: "#6dcbfa",
      magenta: "#dabafa",
      cyan: "#90e1c6",
      white: "#c7c7c7",
      brightBlack: "#686868",
      brightRed: "#f28779",
      brightGreen: "#d5ff80",
      brightYellow: "#ffd173",
      brightBlue: "#73d0ff",
      brightMagenta: "#dfbfff",
      brightCyan: "#95e6cb",
      brightWhite: "#ffffff",
    },
  },

  // ── Monokai Pro ──────────────────────────────────────────────────────
  {
    id: "monokai-pro",
    name: "Monokai Pro",
    appearance: "dark",
    chrome: {
      bgPrimary: "#221f22",
      bgSecondary: "#2d2a2e",
      bgTertiary: "#403e41",
      border: "#5b595c",
      textPrimary: "#fcfcfa",
      textSecondary: "#939293",
      accent: "#78dce8",
      accentHover: "#fc9867",
      danger: "#ff6188",
      success: "#a9dc76",
      warning: "#ffd866",
      diffAddBg: "#1a2c18",
      diffDeleteBg: "#2d1219",
    },
    terminal: {
      background: "#2d2a2e",
      foreground: "#fcfcfa",
      cursor: "#c1c0c0",
      cursorAccent: "#c1c0c0",
      selectionBackground: "#5b595c",
      selectionForeground: "#fcfcfa",
      black: "#2d2a2e",
      red: "#ff6188",
      green: "#a9dc76",
      yellow: "#ffd866",
      blue: "#fc9867",
      magenta: "#ab9df2",
      cyan: "#78dce8",
      white: "#fcfcfa",
      brightBlack: "#727072",
      brightRed: "#ff6188",
      brightGreen: "#a9dc76",
      brightYellow: "#ffd866",
      brightBlue: "#fc9867",
      brightMagenta: "#ab9df2",
      brightCyan: "#78dce8",
      brightWhite: "#fcfcfa",
    },
  },

  // ── Night Owl ────────────────────────────────────────────────────────
  {
    id: "night-owl",
    name: "Night Owl",
    appearance: "dark",
    chrome: {
      bgPrimary: "#010e1a",
      bgSecondary: "#011627",
      bgTertiary: "#0b2942",
      border: "#1e4976",
      textPrimary: "#d6deeb",
      textSecondary: "#8badc1",
      accent: "#82aaff",
      accentHover: "#c792ea",
      danger: "#ef5350",
      success: "#22da6e",
      warning: "#addb67",
      diffAddBg: "#0a2a1a",
      diffDeleteBg: "#2a0e13",
    },
    terminal: {
      background: "#011627",
      foreground: "#d6deeb",
      cursor: "#7e57c2",
      cursorAccent: "#ffffff",
      selectionBackground: "#5f7e97",
      selectionForeground: "#dfe5ee",
      black: "#011627",
      red: "#ef5350",
      green: "#22da6e",
      yellow: "#addb67",
      blue: "#82aaff",
      magenta: "#c792ea",
      cyan: "#21c7a8",
      white: "#ffffff",
      brightBlack: "#575656",
      brightRed: "#ef5350",
      brightGreen: "#22da6e",
      brightYellow: "#ffeb95",
      brightBlue: "#82aaff",
      brightMagenta: "#c792ea",
      brightCyan: "#7fdbca",
      brightWhite: "#ffffff",
    },
  },
];

const DEFAULT_THEME_ID = "catppuccin-frappe";

const themeMap = new Map(themes.map((t) => [t.id, t]));

export function getTheme(id: string): BordTheme {
  return themeMap.get(id) ?? getDefaultTheme();
}

export function getDefaultTheme(): BordTheme {
  return themeMap.get(DEFAULT_THEME_ID)!;
}
